---
title: "Measure and Category on the Line"
format:
  html:
    css: ../../../styles.css
    echo: false
    toc: true
    html-math-method: katex
---

This section covers measure and category on $\mathbb{R}$.

::: {.callout-note icon="false"}
## Theorem 1.1 (Cantor)

For any sequence $\{a_n\}$ of real numbers and for any interval $I$ there exists a point $p$ in $I$ such that $p \not = a_n$ for every $n$
:::

::: {.callout-tip icon="false" collapse="true"}
## Proof

Let $I_1$ be a closed subinterval of $I$ such that $a_1 \not \in I_1$. Let $I_2$ be a closed subinterval of $I_1$ such that $a_2 \not \in I_2$. We can continue this pattern inductively, where $I_n$ is a closed interval of $I_{n-1}$ such that $a_n \not \in I_n$. The nested sequence of closed intervals $I_n$ has a non-empty intersection. If $p \in \bigcap I_n$, then $p \in I$ and $p \not = a_n$ for every $n$.
:::

::: {.callout-note icon="false"}
## Definition

A set $A$ is [**nowhere dense**]{style="color: blue"} if it is dense in no interval on $\mathbb{R}$. This is equivalent to saying that every interval on $\mathbb{R}$ has a subinterval entirely contained in the compliment of $A$. An equivalent definition is that $A$ is *nowhere dense* if and only if $Int(Clos(A)) = \varnothing$
:::

::: {.callout-note icon="false"}
## Theorem 1.2

Nowhere dense sets are closed under certain options, namely:

1.  Any subset of nowhere dense sets is nowhere dense.

2.  The union of finitely many nowhere dense sets is nowhere dense.

3.  The closure of a nowhere dense set is nowhere dense.
:::

::: {.callout-tip icon="false" collapse="true"}
## Proof

1.  **Any subset of nowhere dense sets is nowhere dense.**

Let $A$ be a nowhere dense set. If $B \subseteq A$ is dense in some interval on $\mathbb{R}$, than $A$ must be too, which contradicts our assumption $A$ is nowhere dense. Therefore $B$ is also nowhere dense.

2.  **The union of finitely many nowhere dense sets is nowhere dense.**

If $A_1$ and $A_2$ are nowhere dense, than for each interval $I$ there exist subintervals $I_1$ such that $I_1 \cap A_1 = \varnothing$ and a subinterval $I_2 \subseteq I_1$ such that $I_2 \cap A_2 = \varnothing$. Hence $I_2 \cap (A_1 \cap A_2) = \varnothing$. Thus $A_1 \cup A_2$ is nowhere dense.

3.  **The closure of a nowhere dense set is nowhere dense.**

For this proof we use the second definition of a nowhere dense set, $A$ is nowhere dense if and only iff $Int(Clos(A)) = \varnothing$. Note that $Clos(A) = Clos(Clos(A))$.
:::

::: {.callout-note icon="false"}
## Definition

A set $A$ is [**meagre**]{style="color: blue"} if it is a countable union of nowhere dense sets. A set is [**comeagre**]{style="color: blue"} if its complement is *meagre*.
:::

::: {.callout-caution icon="false"}
## Example

$\mathbb{Q}$ is a meagre set, because it is composed of a countable union of singletons, i.e.

$$
\mathbb{Q} = \bigcup_{q \in \mathbb{Q}} q
$$
:::

::: {.callout-note icon="false"}
## Theorem 1.3 (Baire)

All comeagre sets are dense.
:::

::: {.callout-tip icon="false" collapse="true"}
## Proof

Let $A$ be a meagre set and $A = \bigcup A_n$ be the representation of $A$ as a countable union of nowhere dense sets. Let $I$ be any interval on $\mathbb{R}$. Let $I_1 = I - A_1$, $I_2 = I_1 - A_2$, $I_n = I_{n-1} - A_n$. The interval $\bigcup I_n$ is a non-empty subset of $I - A$. So any interval on $\mathbb{R}$ contains points in $A^c$, therefore $A^c$ is dense in $\mathbb{R}$.
:::

::: {.callout-note icon="false"}
## Corollary

No interval in $\mathbb{R}$ is meagre
:::

::: {.callout-tip icon="false" collapse="true"}
## Proof

Let $A$ be a meagre set. Because every interval contains points in $A^c$, there is no interval fully contained in $A$.
:::

::: {.callout-note icon="false"}
## Theorem 1.4

Any subset of a meagre set is meagre. The union of any countable family of meagre sets is meagre.
:::

The properties above are obvious for meagre sets. However, the closure of a set $A$ is meagre if and only if $A$ is nowhere dense. Therefore the closure of a meagre set may not be meagre.

::: {.callout-note icon="false"}
## Definition

A class (informal collection) of sets that contains countable unions and arbitrary subsets of its members is called a [$\pmb\sigma$-ideal]{style="color: blue"}.
:::

The class of meagre sets is a $\sigma$-ideal, along with the class of countable sets. The class of [**nullsets**]{style="color: blue"} (sets of *measure zero*) also forms a $\sigma$-ideal

::: {.callout-note icon="false"}
## Definition

Let the length of an interval $I$ be given by $|I|$. A set $A \subseteq R$ is called a *nullset* if for all $\varepsilon > 0$, there exist a sequence of intervals $I_n$ such that $A \subset \bigcup I_n$ and $\Sigma |I_n| < \varepsilon$.
:::

::: {.callout-note icon="false"}
## Theorem 1.5 (Borel)

If a finite or infinite sequence of intervals $I_n$ covers an interval $I$, $\Sigma |I_n| \geq |I|$
:::

The proof is too long for me to want to write down. The theorem implies that no interval is a nullset.

Every countable set is both meagre and of measure zero. However, some uncountable sets also have these two properties.

::: {.callout-caution icon="false"}
## Example

The Cantor set $C$ is both meagre and a nullset.

**Meagre**

The Cantor set is nowhere dense, because for any $C_n$, the largest interval is of length $\frac{1}{3^n}$. For any interval $I \subset R$, there exist a sufficiently large $n$ such that a *hole* can be found in $I$.

**Nullset**

The sum of the lengths of all closed intervals for any step $C_n$ is exactly $\frac{2}{3^n}$. There exist a sufficiently large $n$ such that for any $\varepsilon > 0$, the sum of the interval length is below $\varepsilon$.
:::