---
title: "Porous sets"
format:
  html:
    css: ../../../styles.css
    echo: false
    toc: true
    html-math-method: katex
---

There are several ways to define a *small* set, like Meager and Measure-zero. Porous sets are an alternate way to measure how *small* a set is.

## Definition 

A set is porous if every interval $I$ in $\mathbb{R}$ contains an interval $I_2$ completly missing the set, such that $|I_2| = \alpha |I|$ where $0 < \alpha < 1$.

Formalizing this definition requires a few steps.

::: {.callout-note icon="false"}
## Definition

Let $E$ be a set in $\mathbb{R}$, and $x \in \mathbb{R}$. The [**right porosity**]{style="color: blue"} of $E$ at $x$ is denoted $p^+(E,x)$ and is given by

$$
p^+(E,x) = \limsup_{\varepsilon \to 0^+} \frac{k}{k+h}
$$

where $(x + h, x + h + k) \cap E = \varnothing, h + k < \varepsilon$ and $h,k > 0$, and $\sup$ refers to the lowest greater bound. Similary, the [**left porosity**]{style="color: blue"} of $E$, denoted $p^-(E,x)$ is defined by $(x - h - k, x - h) \cap E = \varnothing$

Then the [**porosity**]{style="color: blue"} of $E$ at $x$ is defined by 

$$
p(E,x) = \max\{p^-(E,x),p^+(E,x)\}
$$

It is clear the value of $p$ is inbetween $[0,1]$. We say that $E$ is [**porous at $\bf x$**]{style="color: blue"} if $p(E,x) > 0$, and that $E$ is [**porous**]{style="color: blue"} if $p(E,x) > 0$ for all $x \in E$.

:::

::: {.callout-caution icon="false"}
## Example

Are the following sets porous at $x$?

1. Is the set $E = [0,1]$ porous at $x = \frac{1}{2}$?

Let's start by trying to find the left porosity of $E$ at $x$. It's clear that when $\varepsilon < \frac{1}{2}$, no values of $h,k$ satisfy $(x + h, x + h + k) \cap E = \varnothing, h + k < \varepsilon$. Therefore, the set does not have a defined left porosity. Similary the set does not have a defined right porosity, so the set is not porous at $x = \frac{1}{2}$.


2. Is the set $E = C$ porous at $x = \frac{1}{3}$?

In this case $C$ refers to the Cantor ternary set. At $x = \frac{1}{3}$, it is clear that $p^+(C,\frac{1}{3}) = 1$, because $h$ can get arbitrarily small while completly avoiding $C$. Because $p^-$ can't possibly be greater than $1$, $p(C,\frac{1}{3}) =  1$, and the Cantor ternary set is porous at $x = \frac{1}{3}$.
:::

## Beta-porous

::: {.callout-note icon="false"}
## Definition

Let $A \subseteq \mathbb{R}$, $\beta \in (0,1)$. Then $A$ is $\beta$-porous iff for every $(a,b) \  in \mathbb{R}$, $\exists(a^\prime,b^\prime) \subseteq (a,b)$ such that $(b^\prime - a^\prime) = \beta(b-a)$

:::

## f-porous

A set $A$ is $f$-porous if for some $f$, there exists an $\varepsilon_n$ such that for all intervals $|J| \subset |I|$, there exists an interval $|K| \subset |J|$ such that $$

::: {.callout-note icon="false"}
## Theorem

A set $A$ is $f$-porous $\forall f$ iff $A$ is discrete

:::

::: {.callout-tip icon="false"}
## Proof

If a set is discrete, then we can 



By way of contradition, assume $A$ is not discrete, and $f$-porous for every $f$. Then 

$$
\exists x \in A \mid \forall \varepsilon > 0,\quad \mathcal{B}(x,\varepsilon) - \{x\} \cap A \not = \varnothing
$$

Without loss of generality, let 

$$
\lvert x - x_{n-1} \rvert < \lvert x - {x_n}\rvert
$$

and

$$
|x_{n-1} - x_n| < \frac{x_n - x}{2}
$$

For each $n \in \mathbb{N}$, let $f_n$ be such that

$$
f_n(|x_n - x|) > |x_n - x_{n+1}|
$$

We choose a random interval $x \in I \subset \mathbb{R}$, and let $\varepsilon_{I,n} > 0$ be this intervals associated epsilon for any $f_n$.

Let $J \subset I$ such that $|J| < \varepsilon_{I,n}$ and $n \in \mathbb{N}$. 

Need to show that $|x_n - x_{n-1}| < |x_n - x|/2$. Can't prove.
:::


::: {.callout-tip icon="false"}
## Proof

Suppose $A$ is uncountable. Uncountable sets have the property that there exists some point $x$ that is a limit point from both sides, symbollically.

$$
\exists x \in A \mid \forall \varepsilon > 0
$$

$$
(x-\varepsilon,x) \cap A \not = \varnothing \land (x, x + \varepsilon) \cap A \not = \varnothing
$$

We can now construct a continually decreasing sequence. Let $\{x_n\} \to x$. Without loss of generality, let 

$$
|x - x_n{+1}| < |x_{n+1} - x_n|
$$

Repeating for $y$. approaching from the oppsite side.

Let $\ell n = |x_n - y_n|$, $c_n = |y_n - y_{n+1}|$ and $m_n = |x_n - x_{n+1}|$. 

Let $I \subseteq \mathbb{R}$, $x \in I$. For each $n \in \mathbb{N}$, let 

$$
f_n = \mathbb{R}^+ \to \mathbb{R}^+ \mid f_n(\ell n) > \max\{c_n,m_n\}
$$

And let $\varepsilon_{I_n}$ be the associated value of epsilon. Let $J \subset I$ and $n \in \mathbb{N}$ such that $|J| < \varepsilon_{I,n}$.

Let $J$ be such that $x_n,y_n \in J$. Since $f_n$ is a decreasing function,

$$
f_n(|J|) > f_n(\ell n) > \max\{c_n,m_n\}
$$

Because either $c_n$ or $m_n$ is the biggest hole in $(y_n,x_n)$, there is clearly no hole bigger than $\max\{c_n,m_n\}$. Thus a contradiction, and if a set is $f$-porous for every $f$, then $A$ is not uncountable.
:::

